- name: Get all solc versions
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
  vars:
    solc_versions: "{{ lookup('file', '{{ solc_versions_list }}') | from_yaml }}"
    parity_tags: "{{ lookup('file', '{{ parity_tags_list }}') | from_yaml }}"
  tasks:
    - name: Iterate through parity versions
      include_tasks: perform_for_single_parity_version.yml
      with_items: "{{ parity_tags }}"
      loop_control:
        loop_var: parity_tag